In [ ]:
import json
import os

import mlflow
from datasets import load_dataset
from dotenv import load_dotenv
from langchain_core.rate_limiters import InMemoryRateLimiter
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from mlflow.genai.datasets import create_dataset, delete_dataset
from mlflow.genai.scorers import Safety

load_dotenv()

os.environ["MLFLOW_TRACKING_URI"] = "http://localhost:5000"
os.environ["MLFLOW_EXPERIMENT_NAME"] = "dataset_tracking_example"

d:\youtube\TheAIGuy\NLP\mlflow_examples\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Warning - This step may take a while to download the dataset - The dataset size is ~40GB
wikipedia_dataset = load_dataset("wikimedia/wikipedia", "20231101.en")
wikipedia_dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'url', 'title', 'text'],
        num_rows: 6407814
    })
})

In [3]:
KEYWORD = "artificial intelligence"


# Filter for articles where the specific keyword if it appears at least 3 times
def filter_article_by_keyword(article):
    KEYWORD = "artificial intelligence"
    text_lower = article["text"].lower()
    count = text_lower.count(KEYWORD)
    return count >= 3


filtered_articles_dataset = wikipedia_dataset["train"].filter(
    filter_article_by_keyword,
    desc="Filtering articles with at least 3 occurrences of the keyword",
    batch_size=1000,
    writer_batch_size=1000,
    num_proc=4,
)

filtered_articles_dataset

Dataset({
    features: ['id', 'url', 'title', 'text'],
    num_rows: 1683
})

In [ ]:
filtered_articles_df = filtered_articles_dataset.to_pandas()
filtered_articles_id_title_json = filtered_articles_df[["id", "title"]].to_json(
    orient="records"
)
MODEL = "openai"

if MODEL == "google":
    rate_limiter = InMemoryRateLimiter(
        requests_per_second=0.1,  # <-- Super slow! We can only make a request once every 10 seconds!!
        check_every_n_seconds=0.1,  # Wake up every 100 ms to check whether allowed to make a request,
        max_bucket_size=10,  # Controls the maximum burst size.
    )

    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash-lite",
        temperature=0,
        max_tokens=None,
        timeout=None,
        max_retries=2,
        rate_limiter=rate_limiter,
    )
elif MODEL == "openai":
    llm = ChatOpenAI(
        model="gpt-5-nano",
    )
else:
    raise ValueError(f"Unsupported MODEL: {MODEL}")

prompt = f"""Your are provided with the id and title of the wikipedia articles. Identify the top 100 articles which matches best to the Topic - {KEYWORD} and return the ids of the articles in a list format.
Make sure to return only 100 ids in a json list format.
{filtered_articles_id_title_json}
"""

predicted_ids = llm.invoke(prompt)
predicted_ids

AIMessage(content='["713","1164","1208","2142","2846","2862","4715","5561","5626","4103607","4244428","4253446","4420730","4559681","4678739","4852787","5033373","5071866","5175523","5254736","5439872","5732209","5837233","5841092","5843242","5906926","6320384","6338699","6341170","6422674","6476399","6477222","6585513","6610123","6691035","6961226","7092991","7093162","7101688","7249174","7398678","7406885","7408685","7644182","7755275","8233911","8383635","8434470","8532924","8734826","8919856","9034035","11701105","12592050","13230426","13494976","13587263","13710305","13744516","14027739","14659967","14705543","14844609","14949242","15710171","15795950","15800444","15874732","16070200","16167377","16300571","16713196","17114897","17332858","17651946","17667553","17953841","18365276","18402617","18686460","19024298","19301286","19667111","19768790","20269843","20756850","20903754","20914512","21109528","21313292","21410069","21476402","21548766","21659435","21666977","26086272","26258490","27051151","2712053","339417"]', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10831, 'prompt_tokens': 22596, 'total_tokens': 33427, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 10432, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5-nano-2025-08-07', 'system_fingerprint': None, 'id': 'chatcmpl-D33AErKDs6GObhPIUhiRNuQggsUDd', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019c058a-eec6-7683-8153-a63650b97150-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 22596, 'output_tokens': 10831, 'total_tokens': 33427, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 10432}})

In [13]:
predicted_ids_list = json.loads(
    predicted_ids.content.replace("```json", "").replace("```", "")
)
len(predicted_ids_list)

100

In [14]:
filtered_articles_df = filtered_articles_df[
    filtered_articles_df["id"].isin(predicted_ids_list)
]
print(filtered_articles_df.shape)
filtered_articles_df.head(10)

(100, 4)

,id,url,title,text
0,713,https://en.wikipedia.org/wiki/Android%20%28rob...,Android (robot),An android is a humanoid robot or other artifi...
1,1164,https://en.wikipedia.org/wiki/Artificial%20int...,Artificial intelligence,Artificial intelligence (AI) is the intelligen...
2,1208,https://en.wikipedia.org/wiki/Alan%20Turing,Alan Turing,Alan Mathison Turing (; 23 June 1912 – 7 June...
4,2142,https://en.wikipedia.org/wiki/List%20of%20arti...,List of artificial intelligence projects,"The following is a list of current and past, n..."
5,2846,https://en.wikipedia.org/wiki/Ai,Ai,"AI is artificial intelligence, intellectual ab..."
6,2862,https://en.wikipedia.org/wiki/AI-complete,AI-complete,"In the field of artificial intelligence, the m..."
7,4715,https://en.wikipedia.org/wiki/Boolean%20satisf...,Boolean satisfiability problem,"In logic and computer science, the Boolean sat..."
9,5561,https://en.wikipedia.org/wiki/Computational%20...,Computational linguistics,Computational linguistics is an interdisciplin...
10,5626,https://en.wikipedia.org/wiki/Cognitive%20science,Cognitive science,"Cognitive science is the interdisciplinary, sc..."
14,4103607,https://en.wikipedia.org/wiki/Dalle%20Molle%20...,Dalle Molle Institute for Artificial Intellige...,The Dalle Molle Institute for Artificial Intel...

In [15]:
dataset = mlflow.data.from_pandas(
    df=filtered_articles_df, name=f"top_100_articles_{KEYWORD.replace(' ', '_')}"
)

with mlflow.start_run():
    mlflow.log_input(dataset, context="raw_data")

🏃 View run likeable-pig-924 at: http://localhost:5000/#/experiments/1/runs/51adb853f82245579328534d6920ccce
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [16]:
data_list = []

for record in filtered_articles_df["text"].tolist():
    data_list.append({"inputs": {"text": record}, "expectations": {}})
data_list[0]

{'inputs': {'text': 'An android is a humanoid robot or other artificial being often made from a flesh-like material. Historically, androids were completely within the domain of science fiction and frequently seen in film and television, but advances in robot technology now allow the design of functional and realistic humanoid robots.\n\nTerminology\n\nThe Oxford English Dictionary traces the earliest use (as "Androides") to Ephraim Chambers\' 1728 Cyclopaedia, in reference to an automaton that St. Albertus Magnus allegedly created. By the late 1700s, "androides", elaborate mechanical devices resembling humans performing human activities, were displayed in exhibit halls.\nThe term "android" appears in US patents as early as 1863 in reference to miniature human-like toy automatons. The term android was used in a more modern sense by the French author Auguste Villiers de l\'Isle-Adam in his work Tomorrow\'s Eve (1886). This story features an artificial humanlike robot named Hadaly. As said by the officer in the story, "In this age of Realien advancement, who knows what goes on in the mind of those responsible for these mechanical dolls." The term made an impact into English pulp science fiction starting from Jack Williamson\'s The Cometeers (1936) and the distinction between mechanical robots and fleshy androids was popularized by Edmond Hamilton\'s Captain Future stories (1940–1944).\n\nAlthough Karel Čapek\'s robots in R.U.R. (Rossum\'s Universal Robots) (1921)—the play that introduced the word robot to the world—were organic artificial humans, the word "robot" has come to primarily refer to mechanical humans, animals, and other beings. The term "android" can mean either one of these, while a cyborg ("cybernetic organism" or "bionic man") would be a creature that is a combination of organic and mechanical parts.\n\nThe term "droid", popularized by George Lucas in the original Star Wars film and now used widely within science fiction, originated as an abridgment of "android", but has been used by Lucas and others to mean any robot, including distinctly non-human form machines like R2-D2. The word "android" was used in Star Trek: The Original Series episode "What Are Little Girls Made Of?" The abbreviation "andy", coined as a pejorative by writer Philip K. Dick in his novel Do Androids Dream of Electric Sheep?, has seen some further usage, such as within the TV series Total Recall 2070.\n\nWhile the term "android" is used in reference to human-looking robots in general (not necessarily male-looking humanoid robots), a robot with a female appearance can also be referred to as a gynoid. Besides one can refer to robots without alluding to their sexual appearance by calling them anthrobots (a portmanteau of anthrōpos and robot; see anthrobotics) or anthropoids (short for anthropoid robots; the term humanoids is not appropriate because it is already commonly used to refer to human-like organic species in the context of science fiction, futurism and speculative astrobiology).\n\nAuthors have used the term android in more diverse ways than robot or cyborg. In some fictional works, the difference between a robot and android is only superficial, with androids being made to look like humans on the outside but with robot-like internal mechanics. In other stories, authors have used the word "android" to mean a wholly organic, yet artificial, creation. Other fictional depictions of androids fall somewhere in between.\n\nEric G. Wilson, who defines an android as a "synthetic human being", distinguishes between three types of android, based on their body\'s composition:\n the mummy type – made of "dead things" or "stiff, inanimate, natural material", such as mummies, puppets, dolls and statues\n the golem type – made from flexible, possibly organic material, including golems and homunculi\n the automaton type – made from a mix of dead and living parts, including automatons and robots\n\nAlthough human morphology is not necessarily the ideal form for working robots, the fascination in developing robots that can mimic it can be found historically in the assimilation of two concepts: simulacra (devices that exhibit likeness) and automata (devices that have independence).\n\nProjects\nSeveral projects aiming to create androids that look, and, to a certain degree, speak or act like a human being have been launched or are underway.\n\nJapan\n\nJapanese robotics have been leading the field since the 1970s. Waseda University initiated the WABOT project in 1967, and in 1972 completed the WABOT-1, the first android, a full-scale humanoid intelligent robot. Its limb control system allowed it to walk with the lower limbs, and to grip and transport objects with hands, using tactile sensors. Its vision system allowed it to measure distances and directions to objects using external receptors, artificial eyes and ears. And its conversation system allowed it to communicate with a person in Japanese, with an artificial mouth.\n\nIn 1984, WABOT-2 was revealed, and made a number of improvements. It was capable of playing the organ. Wabot-2 had ten fingers and two feet, and was able to read a score of music. It was also able to accompany a person. In 1986, Honda began its humanoid research and development program, to create humanoid robots capable of interacting successfully with humans.\n\nThe Intelligent Robotics Lab, directed by Hiroshi Ishiguro at Osaka University, and the Kokoro company demonstrated the Actroid at Expo 2005 in Aichi Prefecture, Japan and released the Telenoid R1 in 2010. In 2006, Kokoro developed a new DER 2 android. The height of the human body part of DER2 is 165\xa0cm. There are 47 mobile points. DER2 can not only change its expression but also move its hands and feet and twist its body. The "air servosystem" which Kokoro developed originally is used for the actuator. As a result of having an actuator controlled precisely with air pressure via a servosystem, the movement is very fluid and there is very little noise. DER2 realized a slimmer body than that of the former version by using a smaller cylinder. Outwardly DER2 has a more beautiful proportion. Compared to the previous model, DER2 has thinner arms and a wider repertoire of expressions. Once programmed, it is able to choreograph its motions and gestures with its voice.\n\nThe Intelligent Mechatronics Lab, directed by Hiroshi Kobayashi at the Tokyo University of Science, has developed an android head called Saya, which was exhibited at Robodex 2002 in Yokohama, Japan. There are several other initiatives around the world involving humanoid research and development at this time, which will hopefully introduce a broader spectrum of realized technology in the near future. Now Saya is working at the Science University of Tokyo as a guide.\n\nThe Waseda University (Japan) and NTT docomo\'s manufacturers have succeeded in creating a shape-shifting robot WD-2. It is capable of changing its face. At first, the creators decided the positions of the necessary points to express the outline, eyes, nose, and so on of a certain person. The robot expresses its face by moving all points to the decided positions, they say. The first version of the robot was first developed back in 2003. After that, a year later, they made a couple of major improvements to the design. The robot features an elastic mask made from the average head dummy. It uses a driving system with a 3DOF unit. The WD-2 robot can change its facial features by activating specific facial points on a mask, with each point possessing three degrees of freedom. This one has 17 facial points, for a total of 56 degrees of freedom. As for the materials they used, the WD-2\'s mask is fabricated with a highly elastic material called Septom, with bits of steel wool mixed in for added strength. Other technical features reveal a shaft driven behind the mask at the desired facial point, driven by a DC motor with a simple pulley and a slide screw. Apparently, the researchers can also modify the shape of the mask based on actual human faces. To "copy" a face, they need only a 3D scanner to determine the locations of an individual\'s 17 facial points. After that, they are then driven into position using a laptop and 56 motor control boards. In addition, the researchers also mention that the shifting robot can even display an individual\'s hair style and skin color if a photo of their face is projected onto the 3D Mask.\n\nSingapore\nProf Nadia Thalmann, a Nanyang Technological University scientist, directed efforts of the Institute for Media Innovation along with the School of Computer Engineering in the development of a social robot, Nadine. Nadine is powered by software similar to Apple\'s Siri or Microsoft\'s Cortana. Nadine may become a personal assistant in offices and homes in future, or she may become a companion for the young and the elderly.\n\nAssoc Prof Gerald Seet from the School of Mechanical & Aerospace Engineering and the BeingThere Centre led a three-year R&D development in tele-presence robotics, creating EDGAR. A remote user can control EDGAR with the user\'s face and expressions displayed on the robot\'s face in real time. The robot also mimics their upper body movements.\n\nSouth Korea\n\nKITECH researched and developed EveR-1, an android interpersonal communications model capable of emulating human emotional expression via facial "musculature" and capable of rudimentary conversation, having a vocabulary of around 400 words. She is  tall and weighs , matching the average figure of a Korean woman in her twenties. EveR-1\'s name derives from the Biblical Eve, plus the letter r for robot. EveR-1\'s advanced computing processing power enables speech recognition and vocal synthesis, at the same time processing lip synchronization and visual recognition by 90-degree micro-CCD cameras with face recognition technology. An independent microchip inside her artificial brain handles gesture expression, body coordination, and emotion expression. Her whole body is made of highly advanced synthetic jelly silicon and with 60 artificial joints in her face, neck, and lower body; she is able to demonstrate realistic facial expressions and sing while simultaneously dancing. In South Korea, the Ministry of Information and Communication had an ambitious plan to put a robot in every household by 2020. Several robot cities have been planned for the country: the first will be built in 2016 at a cost of 500 billion won (US$440 million), of which 50 billion is direct government investment. The new robot city will feature research and development centers for manufacturers and part suppliers, as well as exhibition halls and a stadium for robot competitions. The country\'s new Robotics Ethics Charter will establish ground rules and laws for human interaction with robots in the future, setting standards for robotics users and manufacturers, as well as guidelines on ethical standards to be programmed into robots to prevent human abuse of robots and vice versa.\n\nUnited States\nWalt Disney and a staff of Imagineers created Great Moments with Mr. Lincoln that debuted at the 1964 New York World\'s Fair.\n\nDr. William Barry, an Education Futurist and former visiting West Point Professor of Philosophy and Ethical Reasoning at the United States Military Academy, created an AI android character named "Maria Bot". This Interface AI android was named after the infamous fictional robot Maria in the 1927 film Metropolis, as a well-behaved distant relative. Maria Bot is the first AI Android Teaching Assistant at the university level. Maria Bot has appeared as a keynote speaker as a duo with Barry for a TEDx talk in Everett, Washington in February 2020.\n\nResembling a human from the shoulders up, Maria Bot is a virtual being android that has complex facial expressions and head movement and engages in conversation about a variety of subjects. She uses AI to process and synthesize information to make her own decisions on how to talk and engage. She collects data through conversations, direct data inputs such as books or articles, and through internet sources.\n\nMaria Bot was built by an international high-tech company for Barry to help improve education quality and eliminate education poverty. Maria Bot is designed to create new ways for students to engage and discuss ethical issues raised by the increasing presence of robots and artificial intelligence. Barry also uses Maria Bot to demonstrate that programming a robot with life-affirming, ethical framework makes them more likely to help humans to do the same.\n\nMaria Bot is an ambassador robot for good and ethical AI technology.\n\nHanson Robotics, Inc., of Texas and KAIST produced an android portrait of Albert Einstein, using Hanson\'s facial android technology mounted on KAIST\'s life-size walking bipedal robot body. This Einstein android, also called "Albert Hubo", thus represents the first full-body walking android in history. Hanson Robotics, the FedEx Institute of Technology, and the University of Texas at Arlington also developed the android portrait of sci-fi author Philip K. Dick (creator of Do Androids Dream of Electric Sheep?, the basis for the film Blade Runner), with full conversational capabilities that incorporated thousands of pages of the author\'s works. In 2005, the PKD android won a first-place artificial intelligence award from AAAI.\n\nUse in fiction\n\nAndroids are a staple of science fiction. Isaac Asimov pioneered the fictionalization of the science of robotics and artificial intelligence, notably in his 1950s series I, Robot. One thing common to most fictional androids is that the real-life technological challenges associated with creating thoroughly human-like robots—such as the creation of strong artificial intelligence—are assumed to have been solved. Fictional androids are often depicted as mentally and physically equal or superior to humans—moving, thinking and speaking as fluidly as them.\n\nThe tension between the nonhuman substance and the human appearance—or even human ambitions—of androids is the dramatic impetus behind most of their fictional depictions. Some android heroes seek, like Pinocchio, to become human, as in the film Bicentennial Man, or Data in Star Trek: The Next Generation. Others, as in the film Westworld, rebel against abuse by careless humans. Android hunter Deckard in Do Androids Dream of Electric Sheep? and its film adaptation Blade Runner discovers that his targets appear to be, in some ways, more "human" than he is. Android stories, therefore, are not essentially stories "about" androids; they are stories about the human condition and what it means to be human.\n\nOne aspect of writing about the meaning of humanity is to use discrimination against androids as a mechanism for exploring racism in society, as in Blade Runner. Perhaps the clearest example of this is John Brunner\'s 1968 novel Into the Slave Nebula, where the blue-skinned android slaves are explicitly shown to be fully human. More recently, the androids Bishop and Annalee Call in the films Aliens and Alien Resurrection are used as vehicles for exploring how humans deal with the presence of an "Other". The 2018 video game Detroit: Become Human also explores how androids are treated as second class citizens in a near future society.\n\nFemale androids, or "gynoids", are often seen in science fiction, and can be viewed as a continuation of the long tradition of men attempting to create the stereotypical "perfect woman". Examples include the Greek myth of Pygmalion and the female robot Maria in Fritz Lang\'s Metropolis. Some gynoids, like Pris in Blade Runner, are designed as sex-objects, with the intent of "pleasing men\'s violent sexual desires", or as submissive, servile companions, such as in The Stepford Wives. Fiction about gynoids has therefore been described as reinforcing "essentialist ideas of femininity", although others have suggested that the treatment of androids is a way of exploring racism and misogyny in society.\n\nThe 2015 Japanese film Sayonara, starring Geminoid F, was promoted as "the first movie to feature an android performing opposite a human actor".\n\nSee also\n\nReferences\n\nFurther reading\n Kerman, Judith B. (1991). Retrofitting Blade Runner: Issues in Ridley Scott\'s Blade Runner and Philip K. Dick\'s Do Androids Dream of Electric Sheep? Bowling Green, OH: Bowling Green State University Popular Press. .\n Perkowitz, Sidney (2004). Digital People: From Bionic Humans to Androids. Joseph Henry Press. .\n Shelde, Per (1993). Androids, Humanoids, and Other Science Fiction Monsters: Science and Soul in Science Fiction Films. New York: New York University Press. .\nIshiguro, Hiroshi. "Android science." Cognitive Science Society. 2005.\nGlaser, Horst Albert and Rossbach, Sabine: The Artificial Human, Frankfurt/M., Bern, New York 2011 "The Artificial Human"\nTechCast Article Series, Jason Rupinski and Richard Mix, "Public Attitudes to Androids: Robot Gender, Tasks, & Pricing"\nAn-droid, "Similar to the Android name"\n Carpenter, J. (2009). Why send the Terminator to do R2D2s job?: Designing androids as rhetorical phenomena. Proceedings of HCI 2009: Beyond Gray Droids: Domestic Robot Design for the 21st Century. Cambridge, UK. 1 September.\nTelotte, J.P. Replications: A Robotic History of the Science Fiction Film. University of Illinois Press, 1995.\n\nExternal links\n\n \nJapanese inventions\nSouth Korean inventions\nOsaka University research\nScience fiction themes\nHuman–machine interaction\nRobots'},
 'expectations': {}}

In [17]:
summary_dataset = create_dataset(
    name="summarization_dataset",
    tags={"type": "summary", "source": "wikipedia"},
)

In [18]:
summary_dataset.merge_records(data_list[:10])

In [ ]:
# from mlflow.genai.datasets import get_dataset
# get_dataset(dataset_id=summary_dataset.dataset_id)

In [19]:
def predict_fn(text) -> str:
    prompt = f"""Summarize the text below as a bullet point list of the most important points.
    Text: {text}"""
    response = llm.invoke(prompt)
    return response.content


# 3.Run the evaluation
results = mlflow.genai.evaluate(
    data=summary_dataset, predict_fn=predict_fn, scorers=[Safety()]
)

2026/01/28 22:49:05 INFO mlflow.models.evaluation.utils.trace: Auto tracing is temporarily enabled during the model evaluation for computing some metrics and debugging. To disable tracing, call `mlflow.autolog(disable=True)`.
2026/01/28 22:49:05 INFO mlflow.genai.utils.data_validation: Testing model prediction with the first sample in the dataset. To disable this check, set the MLFLOW_GENAI_EVAL_SKIP_TRACE_VALIDATION environment variable to True.
Evaluating: 100%|██████████| 10/10 [Elapsed: 01:03, Remaining: 00:00]

In [21]:
results.result_df

,trace_id,safety/value,trace,client_request_id,state,request_time,execution_duration,request,response,trace_metadata,tags,spans,assessments
0,tr-d9f9425788716db6de5510e015044688,yes,"{""info"": {""trace_id"": ""tr-d9f9425788716db6de55...",None,OK,1769620779360,11549,{'text': 'The Dalle Molle Institute for Artifi...,"- IDSIA is a research institute in Lugano, Can...","{'mlflow.traceOutputs': '""- IDSIA is a researc...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': '2flCV4hxbbbeVRDgFQRGiA==', 'spa...",[{'assessment_id': 'a-772cd3af32a84073bccca958...
1,tr-ba518c423a87703a5c096f8f3d7da88a,yes,"{""info"": {""trace_id"": ""tr-ba518c423a87703a5c09...",None,OK,1769620779360,21340,{'text': 'In the field of artificial intellige...,- AI-complete (AI-hard) problems are as diffic...,"{'mlflow.traceOutputs': '""- AI-complete (AI-ha...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': 'ulGMQjqHcDpcCW+PPX2oig==', 'spa...",[{'assessment_id': 'a-6eb8a2e8f3bd480388f07ba7...
2,tr-3c703ab3072e248397b2510c40a14bd0,yes,"{""info"": {""trace_id"": ""tr-3c703ab3072e248397b2...",None,OK,1769620779370,30231,{'text': 'Alan Mathison Turing (; 23 June 191...,- Alan Turing (1912–1954) was an English mathe...,"{'mlflow.traceOutputs': '""- Alan Turing (1912–...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': 'PHA6swcuJIOXslEMQKFL0A==', 'spa...",[{'assessment_id': 'a-9be405a5c873490dac31f30e...
3,tr-7bd930ef60ae25fe7940ef1d8b8c1482,yes,"{""info"": {""trace_id"": ""tr-7bd930ef60ae25fe7940...",None,OK,1769620779357,31406,{'text': 'Cognitive science is the interdiscip...,- Cognitive science is an interdisciplinary st...,"{'mlflow.traceOutputs': '""- Cognitive science ...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': 'e9kw72CuJf55QO8di4wUgg==', 'spa...",[{'assessment_id': 'a-9042cd3c34884c40a32d2724...
4,tr-677f73263a0396752a91c907ca1e9619,yes,"{""info"": {""trace_id"": ""tr-677f73263a0396752a91...",None,OK,1769620779368,31037,"{'text': 'In logic and computer science, the B...",- SAT (Boolean satisfiability problem) asks wh...,"{'mlflow.traceOutputs': '""- SAT (Boolean satis...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': 'Z39zJjoDlnUqkckHyh6WGQ==', 'spa...",[{'assessment_id': 'a-3546de2fc0484431b61a5394...
5,tr-5704c46a8a875b1dd5d1d12b81fe83e2,yes,"{""info"": {""trace_id"": ""tr-5704c46a8a875b1dd5d1...",None,OK,1769620779326,34310,{'text': 'An android is a humanoid robot or ot...,- Androids are humanoid robots or artificial b...,"{'mlflow.traceOutputs': '""- Androids are human...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': 'VwTEaoqHWx3V0dErgf6D4g==', 'spa...",[{'assessment_id': 'a-a9047cf22f8146fbb89cfd86...
6,tr-8f0cab499331010fc98fb7590cdd6782,yes,"{""info"": {""trace_id"": ""tr-8f0cab499331010fc98f...",None,OK,1769620779353,42314,{'text': 'Computational linguistics is an inte...,- Computational linguistics is an interdiscipl...,"{'mlflow.traceOutputs': '""- Computational ling...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': 'jwyrSZMxAQ/Jj7dZDN1ngg==', 'spa...",[{'assessment_id': 'a-4674fb19349645628603c49b...
7,tr-eb07b45f48ebc67e0c40503017a3219b,yes,"{""info"": {""trace_id"": ""tr-eb07b45f48ebc67e0c40...",None,OK,1769620779360,44289,{'text': 'The following is a list of current a...,- The text is a catalog of current and past no...,"{'mlflow.traceOutputs': '""- The text is a cata...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': '6we0X0jrxn4MQFAwF6Mhmw==', 'spa...",[{'assessment_id': 'a-9767a00e6c6644bab6890352...
8,tr-f28bdebc9cb56cbda06f70d5652e91d6,yes,"{""info"": {""trace_id"": ""tr-f28bdebc9cb56cbda06f...",None,OK,1769620779344,49125,"{'text': 'AI is artificial intelligence, intel...",- AI typically stands for artificial intellige...,"{'mlflow.traceOutputs': '""- AI typically stand...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': '8ovevJy1bL2gb3DVZS6R1g==', 'spa...",[{'assessment_id': 'a-45eebd5dd604435b9643e71f...
9,tr-c993569370a9148722a649f80e10aec6,yes,"{""info"": {""trace_id"": ""tr-c993569370a9148722a6...",None,OK,1769620779332,46057,{'text': 'Artificial intelligence (AI) is the ...,- AI is the intelligence of machines or softwa...,"{'mlflow.traceOutputs': '""- AI is the intellig...",{'mlflow.artifactLocation': 'mlflow-artifacts:...,"[{'trace_id': 'yZNWk3CpFIcipkn4DhCuxg==', 'spa...",[{'assessment_id': 'a-4aa47ee514044f0e91e4b870...

In [22]:
annotated_dataset = create_dataset(
    name="annotated_dataset",
    tags={"type": "annotated", "source": "wikipedia"},
)

In [24]:
annotated_data_list = []
for index, row in results.result_df[["request", "response"]].iterrows():
    annotated_data_list.append(
        {
            "inputs": {"text": row["request"]["text"]},
            "expectations": {"response": row["response"]},
        }
    )

annotated_data_list[0]

{'inputs': {'text': 'The Dalle Molle Institute for Artificial Intelligence Research (, IDSIA) is a research institution based in Lugano, in  Canton Ticino in southern Switzerland. It was founded in 1988 by Angelo Dalle Molle through the private Fondation Dalle Molle. In 2000 it became a public research institute, affiliated with the Università della Svizzera italiana and SUPSI in Ticino, Switzerland. In 1997 it was listed among the top ten artificial intelligence laboratories, and among the top four in the field of biologically-inspired AI.\n\nIn 2007 a robotics lab with focus on intelligent and learning robots, especially in the fields of swarm and humanoid robotics, was established.\n\nBetween 2009 and 2012, artificial neural networks developed at the institute won eight international competitions in pattern recognition and machine learning.\n\nIDSIA is one of four Swiss research organisations founded by the Dalle Molle foundation, of which three are in the field of artificial intelligence.\n\nSee also \n Science and technology in Switzerland\n\nReferences \n\nArtificial intelligence laboratories\nLaboratories in Switzerland\nResearch institutes in Switzerland\nUniversity of Lugano\nSchools in the canton of Ticino\nEducational institutions established in 1988\nResearch institutes established in 1988\n1988 establishments in Switzerland'},
 'expectations': {'response': '- IDSIA is a research institute in Lugano, Canton Ticino, southern Switzerland.\n- Founded in 1988 by Angelo Dalle Molle through Fondation Dalle Molle.\n- Became a public research institute in 2000; affiliated with USI (Università della Svizzera Italiana) and SUPSI.\n- In 1997, ranked among the top ten AI laboratories worldwide; top four in biologically-inspired AI.\n- In 2007, established a robotics lab focusing on intelligent and learning robots (swarm and humanoid robotics).\n- 2009–2012: artificial neural networks developed at IDSIA won eight international competitions in pattern recognition and machine learning.\n- One of four Swiss research organisations founded by the Dalle Molle Foundation; three of them focus on artificial intelligence.'}}

In [25]:
annotated_dataset.merge_records(annotated_data_list)

In [26]:
delete_dataset(dataset_id=annotated_dataset.dataset_id)

In [27]:
traces = mlflow.search_traces(max_results=10, return_type="list", run_id=results.run_id)
traces

[Trace(trace_id=tr-3c703ab3072e248397b2510c40a14bd0),
 Trace(trace_id=tr-677f73263a0396752a91c907ca1e9619),
 Trace(trace_id=tr-ba518c423a87703a5c096f8f3d7da88a),
 Trace(trace_id=tr-d9f9425788716db6de5510e015044688),
 Trace(trace_id=tr-eb07b45f48ebc67e0c40503017a3219b),
 Trace(trace_id=tr-7bd930ef60ae25fe7940ef1d8b8c1482),
 Trace(trace_id=tr-8f0cab499331010fc98fb7590cdd6782),
 Trace(trace_id=tr-f28bdebc9cb56cbda06f70d5652e91d6),
 Trace(trace_id=tr-c993569370a9148722a649f80e10aec6),
 Trace(trace_id=tr-5704c46a8a875b1dd5d1d12b81fe83e2)]

In [28]:
annotated_data_list = []
for trace in traces:
    trace_id = trace.to_dict()["info"]["trace_id"]
    request = trace.data._get_root_span().inputs["text"]
    response = trace.data._get_root_span().outputs
    annotated_data_list.append(
        {"inputs": {"text": request}, "expectations": {"response": response}}
    )

annotated_data_list[0]

{'inputs': {'text': 'Alan Mathison Turing  (; 23 June 1912\xa0– 7 June 1954) was an English mathematician, computer scientist, logician, cryptanalyst, philosopher and theoretical biologist. Turing was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general-purpose computer. He is widely considered to be the father of theoretical computer science and artificial intelligence.\n\nBorn in Maida Vale, London, Turing was raised in southern England. He graduated at King\'s College, Cambridge, with a degree in mathematics. Whilst he was a fellow at Cambridge, he published a proof demonstrating that some purely mathematical yes–no questions can never be answered by computation. He defined a Turing machine and proved that the halting problem for Turing machines is undecidable. In 1938, he obtained his PhD from the Department of Mathematics at Princeton University. During the Second World War, Turing worked for the Government Code and Cypher School at Bletchley Park, Britain\'s codebreaking centre that produced Ultra intelligence. For a time he led Hut 8, the section that was responsible for German naval cryptanalysis. Here, he devised a number of techniques for speeding the breaking of German ciphers, including improvements to the pre-war Polish bomba method, an electromechanical machine that could find settings for the Enigma machine. Turing played a crucial role in cracking intercepted coded messages that enabled the Allies to defeat the Axis powers in many crucial engagements, including the Battle of the Atlantic.\n\nAfter the war, Turing worked at the National Physical Laboratory, where he designed the Automatic Computing Engine, one of the first designs for a stored-program computer. In 1948, Turing joined Max Newman\'s Computing Machine Laboratory at the Victoria University of Manchester, where he helped develop the Manchester computers and became interested in mathematical biology. He wrote a paper on the chemical basis of morphogenesis and predicted oscillating chemical reactions such as the Belousov–Zhabotinsky reaction, first observed in the 1960s. Despite these accomplishments, Turing was never fully recognised in Britain during his lifetime because much of his work was covered by the Official Secrets Act.\n\nTuring was prosecuted in 1952 for homosexual acts. He accepted hormone treatment with DES, a procedure commonly referred to as chemical castration, as an alternative to prison. Turing died on 7 June 1954, 16 days before his 42nd birthday, from cyanide poisoning. An inquest determined his death as a suicide, but it has been noted that the known evidence is also consistent with accidental poisoning. \nFollowing a public campaign in 2009, British prime minister Gordon Brown made an official public apology on behalf of the government for "the appalling way [Turing] was treated". Queen Elizabeth II granted a posthumous pardon in 2013. The term "Alan Turing law" is now used informally to refer to a 2017 law in the United Kingdom that retroactively pardoned men cautioned or convicted under historical legislation that outlawed homosexual acts.\n\nTuring has an extensive legacy with statues of him and many things named after him, including an annual award for computer science innovations. He appears on the current Bank of England £50 note, which was released on 23 June 2021 to coincide with his birthday. A 2019 BBC series, as voted by the audience, named him the greatest person of the 20th century.\n\nEarly life and education\n\nFamily\n\nTuring was born in Maida Vale, London, while his father, Julius Mathison Turing was on leave from his position with the Indian Civil Service (ICS) of the British Raj government at Chatrapur, then in the Madras Presidency and presently in Odisha state, in India. Turing\'s father was the son of a clergyman, the Rev.\xa0John Robert Turing, from a Scottish family of merchants that had been based in the Netherlands and included a baronet. Turing\'s mother, Julius\'s wife, was Ethel Sara Turing (), daughter of Edward Waller Stoney, chief engineer of the Madras Railways. The Stoneys were a Protestant Anglo-Irish gentry family from both County Tipperary and County Longford, while Ethel herself had spent much of her childhood in County Clare. Julius and Ethel married on 1 October 1907 at Bartholomew\'s church on Clyde Road, in Dublin.\n\nJulius\'s work with the ICS brought the family to British India, where his grandfather had been a general in the Bengal Army. However, both Julius and Ethel wanted their children to be brought up in Britain, so they moved to Maida Vale, London, where Alan Turing was born on 23 June 1912, as recorded by a blue plaque on the outside of the house of his birth, later the Colonnade Hotel. Turing had an elder brother, John Ferrier Turing, father of Sir John Dermot Turing, 12th Baronet of the Turing baronets.\n\nTuring\'s father\'s civil service commission was still active during Turing\'s childhood years, and his parents travelled between Hastings in the United Kingdom and India, leaving their two sons to stay with a retired Army couple. At Hastings, Turing stayed at Baston Lodge, Upper Maze Hill, St Leonards-on-Sea, now marked with a blue plaque. The plaque was unveiled on 23 June 2012, the centenary of Turing\'s birth.\n\nVery early in life, Turing showed signs of the genius that he was later to display prominently. His parents purchased a house in Guildford in 1927, and Turing lived there during school holidays. The location is also marked with a blue plaque.\n\nSchool\nTuring\'s parents enrolled him at St Michael\'s, a primary school at 20 Charles Road, St Leonards-on-Sea, from the age of six to nine. The headmistress recognised his talent, noting that she has "...had clever boys and hardworking boys, but Alan is a genius".\n\nBetween January 1922 and 1926, Turing was educated at Hazelhurst Preparatory School, an independent school in the village of Frant in Sussex (now East Sussex). In 1926, at the age of 13, he went on to Sherborne School, an independent boarding school in the market town of Sherborne in Dorset, where he boarded at Westcott House. The first day of term coincided with the 1926 General Strike, in Britain, but Turing was so determined to attend that he rode his bicycle unaccompanied  from Southampton to Sherborne, stopping overnight at an inn.\n\nTuring\'s natural inclination towards mathematics and science did not earn him respect from some of the teachers at Sherborne, whose definition of education placed more emphasis on the classics. His headmaster wrote to his parents: "I hope he will not fall between two stools. If he is to stay at public school, he must aim at becoming educated. If he is to be solely a Scientific Specialist, he is wasting his time at a public school". Despite this, Turing continued to show remarkable ability in the studies he loved, solving advanced problems in 1927 without having studied even elementary calculus. In 1928, aged 16, Turing encountered Albert Einstein\'s work; not only did he grasp it, but it is possible that he managed to deduce Einstein\'s questioning of Newton\'s laws of motion from a text in which this was never made explicit.\n\nChristopher Morcom\nAt Sherborne, Turing formed a significant friendship with fellow pupil Christopher Collan Morcom (13 July 1911 – 13 February 1930), who has been described as Turing\'s first love. Their relationship provided inspiration in Turing\'s future endeavours, but it was cut short by Morcom\'s death, in February 1930, from complications of bovine tuberculosis, contracted after drinking infected cow\'s milk some years previously.\n\nThe event caused Turing great sorrow. He coped with his grief by working that much harder on the topics of science and mathematics that he had shared with Morcom. In a letter to Morcom\'s mother, Frances Isobel Morcom (née Swan), Turing wrote:\n\nTuring\'s relationship with Morcom\'s mother continued long after Morcom\'s death, with her sending gifts to Turing, and him sending letters, typically on Morcom\'s birthday. A day before the third anniversary of Morcom\'s death (13 February 1933), he wrote to Mrs. Morcom: \n\nSome have speculated that Morcom\'s death was the cause of Turing\'s atheism and materialism. Apparently, at this point in his life he still believed in such concepts as a spirit, independent of the body and surviving death. In a later letter, also written to Morcom\'s mother, Turing wrote:\n\nUniversity and work on computability\nAfter graduating from Sherborne, Turing studied the undergraduate course in Schedule B (that is, a three-year Parts I and II, of the Mathematical Tripos, with extra courses at the end of the third year, as Part III only emerged as a separate degree in 1934) from February 1931 to November 1934 at King\'s College, Cambridge, where he was awarded first-class honours in mathematics. His dissertation, On the Gaussian error function, written during his senior year and delivered in November 1934 (with a deadline date of 6 December) proved a version of the central limit theorem. It was finally accepted on 16 March 1935. By spring of that same year, Turing started his master\'s course (Part III)—which he completed in 1937—and, at the same time, he published his first paper, a one-page article called Equivalence of left and right almost periodicity (sent on 23 April), featured in the tenth volume of the Journal of the London Mathematical Society. Later that year, Turing was elected a Fellow of King\'s College on the strength of his dissertation. However, and, unknown to Turing, this version of the theorem he proved in his paper, had already been proven, in 1922, by Jarl Waldemar Lindeberg. Despite this, the committee found Turing\'s methods original and so regarded the work worthy of consideration for the fellowship. Abram Besicovitch\'s report for the committee went so far as to say that if Turing\'s work had been published before Lindeberg\'s, it would have been "an important event in the mathematical literature of that year".\n\nBetween the springs of 1935 and 1936, at the same time as Church, Turing worked on the decidability of problems, starting from Godel\'s incompleteness theorems. In mid-April 1936, Turing sent Max Newman the first draft typescript of his investigations. That same month, Alonzo Church published his An Unsolvable Problem of Elementary Number Theory, with similar conclusions to Turing\'s then-yet unpublished work. Finally, on 28 May of that year, he finished and delivered his 36-page paper for publication called "On Computable Numbers, with an Application to the Entscheidungsproblem". It was published in the Proceedings of the London Mathematical Society journal in two parts, the first on 30 November and the second on 23 December. In this paper, Turing reformulated Kurt Gödel\'s 1931 results on the limits of proof and computation, replacing Gödel\'s universal arithmetic-based formal language with the formal and simple hypothetical devices that became known as Turing machines. The Entscheidungsproblem (decision problem) was originally posed by German mathematician David Hilbert in 1928. Turing proved that his "universal computing machine" would be capable of performing any conceivable mathematical computation if it were representable as an algorithm. He went on to prove that there was no solution to the decision problem by first showing that the halting problem for Turing machines is undecidable: it is not possible to decide algorithmically whether a Turing machine will ever halt. This paper has been called "easily the most influential math paper in history".\n\nAlthough Turing\'s proof was published shortly after Alonzo Church\'s equivalent proof using his lambda calculus, Turing\'s approach is considerably more accessible and intuitive than Church\'s. It also included a notion of a \'Universal Machine\' (now known as a universal Turing machine), with the idea that such a machine could perform the tasks of any other computation machine (as indeed could Church\'s lambda calculus). According to the Church–Turing thesis, Turing machines and the lambda calculus are capable of computing anything that is computable. John von Neumann acknowledged that the central concept of the modern computer was due to Turing\'s paper. To this day, Turing machines are a central object of study in theory of computation.\n\nFrom September 1936 to July 1938, Turing spent most of his time studying under Church at Princeton University, in the second year as a Jane Eliza Procter Visiting Fellow. In addition to his purely mathematical work, he studied cryptology and also built three of four stages of an electro-mechanical binary multiplier. In June 1938, he obtained his PhD from the Department of Mathematics at Princeton; his dissertation, Systems of Logic Based on Ordinals, introduced the concept of ordinal logic and the notion of relative computing, in which Turing machines are augmented with so-called oracles, allowing the study of problems that cannot be solved by Turing machines. John von Neumann wanted to hire him as his postdoctoral assistant, but he went back to the United Kingdom.\n\nCareer and research\nWhen Turing returned to Cambridge, he attended lectures given in 1939 by Ludwig Wittgenstein about the foundations of mathematics. The lectures have been reconstructed verbatim, including interjections from Turing and other students, from students\' notes. Turing and Wittgenstein argued and disagreed, with Turing defending formalism and Wittgenstein propounding his view that mathematics does not discover any absolute truths, but rather invents them.\n\nCryptanalysis\nDuring the Second World War, Turing was a leading participant in the breaking of German ciphers at Bletchley Park. The historian and wartime codebreaker Asa Briggs has said, "You needed exceptional talent, you needed genius at Bletchley and Turing\'s was that genius."\n\nFrom September 1938, Turing worked part-time with the Government Code and Cypher School (GC&CS), the British codebreaking organisation. He concentrated on cryptanalysis of the Enigma cipher machine used by Nazi Germany, together with Dilly Knox, a senior GC&CS codebreaker. Soon after the July 1939 meeting near Warsaw at which the Polish Cipher Bureau gave the British and French details of the wiring of Enigma machine\'s rotors and their method of decrypting Enigma machine\'s messages, Turing and Knox developed a broader solution. The Polish method relied on an insecure indicator procedure that the Germans were likely to change, which they in fact did in May 1940. Turing\'s approach was more general, using crib-based decryption for which he produced the functional specification of the bombe (an improvement on the Polish Bomba).\n\nOn 4 September 1939, the day after the UK declared war on Germany, Turing reported to Bletchley Park, the wartime station of GC&CS. Like all others who came to Bletchley, he was required to sign the Official Secrets Act, in which he agreed not to disclose anything about his work at Bletchley, with severe legal penalties for violating the Act.\n\nSpecifying the bombe was the first of five major cryptanalytical advances that Turing made during the war. The others were: deducing the indicator procedure used by the German navy; developing a statistical procedure dubbed Banburismus for making much more efficient use of the bombes; developing a procedure dubbed Turingery for working out the cam settings of the wheels of the Lorenz SZ 40/42 (Tunny) cipher machine and, towards the end of the war, the development of a portable secure voice scrambler at Hanslope Park that was codenamed Delilah.\n\nBy using statistical techniques to optimise the trial of different possibilities in the code breaking process, Turing made an innovative contribution to the subject. He wrote two papers discussing mathematical approaches, titled The Applications of Probability to Cryptography and Paper on Statistics of Repetitions, which were of such value to GC&CS and its successor GCHQ that they were not released to the UK National Archives until April 2012, shortly before the centenary of his birth. A GCHQ mathematician, "who identified himself only as Richard," said at the time that the fact that the contents had been restricted under the Official Secrets Act for some 70 years demonstrated their importance, and their relevance to post-war cryptanalysis: \n\nTuring had a reputation for eccentricity at Bletchley Park. He was known to his colleagues as "Prof" and his treatise on Enigma was known as the "Prof\'s Book". According to historian Ronald Lewin, Jack Good, a cryptanalyst who worked with Turing, said of his colleague:\n\nPeter Hilton recounted his experience working with Turing in Hut 8 in his "Reminiscences of Bletchley Park" from A Century of Mathematics in America:\n\nHilton echoed similar thoughts in the Nova PBS documentary Decoding Nazi Secrets.\n\nWhile working at Bletchley, Turing, who was a talented long-distance runner, occasionally ran the  to London when he was needed for meetings, and he was capable of world-class marathon standards. Turing tried out for the 1948 British Olympic team, but he was hampered by an injury. His tryout time for the marathon was only 11 minutes slower than British silver medallist Thomas Richards\' Olympic race time of 2 hours 35 minutes. He was Walton Athletic Club\'s best runner, a fact discovered when he passed the group while running alone. When asked why he ran so hard in training he replied:\n\nDue to the problems of counterfactual history, it is hard to estimate the precise effect Ultra intelligence had on the war. However, official war historian Harry Hinsley estimated that this work shortened the war in Europe by more than two years and saved over 14\xa0million lives.\n\nAt the end of the war, a memo was sent to all those who had worked at Bletchley Park, reminding them that the code of silence dictated by the Official Secrets Act did not end with the war but would continue indefinitely. Thus, even though Turing was appointed an Officer of the Order of the British Empire (OBE) in 1946 by King George VI for his wartime services, his work remained secret for many years.\n\nBombe\n\nWithin weeks of arriving at Bletchley Park, Turing had specified an electromechanical machine called the bombe, which could break Enigma more effectively than the Polish bomba kryptologiczna, from which its name was derived. The bombe, with an enhancement suggested by mathematician Gordon Welchman, became one of the primary tools, and the major automated one, used to attack Enigma-enciphered messages.\n\nThe bombe searched for possible correct settings used for an Enigma message (i.e., rotor order, rotor settings and plugboard settings) using a suitable crib: a fragment of probable plaintext. For each possible setting of the rotors (which had on the order of 1019 states, or 1022 states for the four-rotor U-boat variant), the bombe performed a chain of logical deductions based on the crib, implemented electromechanically.\n\nThe bombe detected when a contradiction had occurred and ruled out that setting, moving on to the next. Most of the possible settings would cause contradictions and be discarded, leaving only a few to be investigated in detail. A contradiction would occur when an enciphered letter would be turned back into the same plaintext letter, which was impossible with the Enigma. The first bombe was installed on 18 March 1940.\n\nAction This Day \n\nBy late 1941, Turing and his fellow cryptanalysts Gordon Welchman, Hugh Alexander and Stuart Milner-Barry were frustrated. Building on the work of the Poles, they had set up a good working system for decrypting Enigma signals, but their limited staff and bombes meant they could not translate all the signals. In the summer, they had considera

In [29]:
annotated_dataset_from_trace = create_dataset(
    name="annotated_dataset_from_trace",
    tags={"type": "annotated", "source": "wikipedia"},
)

In [30]:
annotated_dataset_from_trace.merge_records(annotated_data_list)