In [ ]:
import json
import os

import mlflow
from datasets import load_dataset
from dotenv import load_dotenv
from langchain_core.rate_limiters import InMemoryRateLimiter
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from mlflow.genai.datasets import create_dataset, delete_dataset
from mlflow.genai.scorers.phoenix import Toxicity

load_dotenv()

os.environ["MLFLOW_TRACKING_URI"] = "http://localhost:5000"
os.environ["MLFLOW_EXPERIMENT_NAME"] = "dataset_tracking_example"

In [4]:
# Warning - This step may take a while to download the dataset - The dataset size is ~40GB
wikipedia_dataset = load_dataset("wikimedia/wikipedia", "20231101.en")
wikipedia_dataset

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'url', 'title', 'text'],
        num_rows: 6407814
    })
})

In [5]:
KEYWORD = "artificial intelligence"


# Filter for articles where the specific keyword if it appears at least 3 times
def filter_article_by_keyword(article):
    KEYWORD = "artificial intelligence"
    text_lower = article["text"].lower()
    count = text_lower.count(KEYWORD)
    return count >= 3


filtered_articles_dataset = wikipedia_dataset["train"].filter(
    filter_article_by_keyword,
    desc="Filtering articles with at least 3 occurrences of the keyword",
    batch_size=1000,
    writer_batch_size=1000,
    num_proc=4,
)

filtered_articles_dataset

Dataset({
    features: ['id', 'url', 'title', 'text'],
    num_rows: 1683
})

In [ ]:
filtered_articles_df = filtered_articles_dataset.to_pandas()
filtered_articles_id_title_json = filtered_articles_df[["id", "title"]].to_json(
    orient="records"
)
MODEL = "openai"

if MODEL == "google":
    rate_limiter = InMemoryRateLimiter(
        requests_per_second=0.1,  # <-- Super slow! We can only make a request once every 10 seconds!!
        check_every_n_seconds=0.1,  # Wake up every 100 ms to check whether allowed to make a request,
        max_bucket_size=10,  # Controls the maximum burst size.
    )

    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash-lite",
        temperature=0,
        max_tokens=None,
        timeout=None,
        max_retries=2,
        rate_limiter=rate_limiter,
    )
elif MODEL == "openai":
    llm = ChatOpenAI(
        model="gpt-5-nano",
    )
else:
    raise ValueError(f"Unsupported MODEL: {MODEL}")

prompt = f"""Your are provided with the id and title of the wikipedia articles. Identify the top 100 articles which matches best to the Topic - {KEYWORD} and return the ids of the articles in a list format.
Make sure to return only 100 ids in a json list format.
{filtered_articles_id_title_json}
"""

predicted_ids = llm.invoke(prompt)
predicted_ids

AIMessage(content='["713","1164","1208","2142","2846","2862","4715","5323","5561","5626","5703","4075738","4103607","4168072","4244428","4244882","4253446","4325491","4357120","4384927","4395638","4420730","4513331","4522868","4559681","4565055","4593326","4678739","4733844","4843650","4848621","4852787","4920830","4986640","5033373","5065056","5069239","5071866","5175523","5192353","5254736","5276122","5356861","5362865","5368665","5397677","5415830","5439872","5589387","5649586","5725671","5732209","5837233","5841092","5843242","5906926","6112811","6320384","6338699","6476399","6477222","6501490","6585513","6610123","6691035","7092991","7093162","7101688","71016058","71106184","71116611","71151961","71642695","71664574","71692942","71700540","71751381","71851483","71974276","72093304","72417803","72514599","73291899","73312151","73363598","73400769","73455792","73645807","73682940","73849538","73897657","73930043","74045044","74091926","74185828","74209694","74209862","74226922","74234356","74265059"]', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 24208, 'prompt_tokens': 22596, 'total_tokens': 46804, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 23808, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-5-nano-2025-08-07', 'system_fingerprint': None, 'id': 'chatcmpl-D5vNhncu5i4faehtCy24ZVuHiBpPs', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019c2e60-3b2a-7cc2-b05a-a93e1566d4f5-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 22596, 'output_tokens': 24208, 'total_tokens': 46804, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 23808}})

In [9]:
predicted_ids_list = json.loads(
    predicted_ids.content.replace("```json", "").replace("```", "")
)
len(predicted_ids_list)

100

In [10]:
filtered_articles_df = filtered_articles_df[
    filtered_articles_df["id"].isin(predicted_ids_list)
]
print(filtered_articles_df.shape)
filtered_articles_df.head(10)

(100, 4)

,id,url,title,text
0,713,https://en.wikipedia.org/wiki/Android%20%28rob...,Android (robot),An android is a humanoid robot or other artifi...
1,1164,https://en.wikipedia.org/wiki/Artificial%20int...,Artificial intelligence,Artificial intelligence (AI) is the intelligen...
2,1208,https://en.wikipedia.org/wiki/Alan%20Turing,Alan Turing,Alan Mathison Turing (; 23 June 1912 – 7 June...
4,2142,https://en.wikipedia.org/wiki/List%20of%20arti...,List of artificial intelligence projects,"The following is a list of current and past, n..."
5,2846,https://en.wikipedia.org/wiki/Ai,Ai,"AI is artificial intelligence, intellectual ab..."
6,2862,https://en.wikipedia.org/wiki/AI-complete,AI-complete,"In the field of artificial intelligence, the m..."
7,4715,https://en.wikipedia.org/wiki/Boolean%20satisf...,Boolean satisfiability problem,"In logic and computer science, the Boolean sat..."
8,5323,https://en.wikipedia.org/wiki/Computer%20science,Computer science,"Computer science is the study of computation, ..."
9,5561,https://en.wikipedia.org/wiki/Computational%20...,Computational linguistics,Computational linguistics is an interdisciplin...
10,5626,https://en.wikipedia.org/wiki/Cognitive%20science,Cognitive science,"Cognitive science is the interdisciplinary, sc..."

In [11]:
dataset = mlflow.data.from_pandas(
    df=filtered_articles_df, name=f"top_100_articles_{KEYWORD.replace(' ', '_')}"
)

with mlflow.start_run():
    mlflow.log_input(dataset, context="raw_data")

🏃 View run dazzling-kit-348 at: http://localhost:5000/#/experiments/1/runs/21ba51fbfd1145be93bffe7711d1cb07
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [12]:
data_list = []

for record in filtered_articles_df["text"].tolist():
    data_list.append({"inputs": {"text": record}, "expectations": {}})
data_list[0]

{'inputs': {'text': 'An android is a humanoid robot or other artificial being often made from a flesh-like material. Historically, androids were completely within the domain of science fiction and frequently seen in film and television, but advances in robot technology now allow the design of functional and realistic humanoid robots.\n\nTerminology\n\nThe Oxford English Dictionary traces the earliest use (as "Androides") to Ephraim Chambers\' 1728 Cyclopaedia, in reference to an automaton that St. Albertus Magnus allegedly created. By the late 1700s, "androides", elaborate mechanical devices resembling humans performing human activities, were displayed in exhibit halls.\nThe term "android" appears in US patents as early as 1863 in reference to miniature human-like toy automatons. The term android was used in a more modern sense by the French author Auguste Villiers de l\'Isle-Adam in his work Tomorrow\'s Eve (1886). This story features an artificial humanlike robot named Hadaly. As said by the officer in the story, "In this age of Realien advancement, who knows what goes on in the mind of those responsible for these mechanical dolls." The term made an impact into English pulp science fiction starting from Jack Williamson\'s The Cometeers (1936) and the distinction between mechanical robots and fleshy androids was popularized by Edmond Hamilton\'s Captain Future stories (1940–1944).\n\nAlthough Karel Čapek\'s robots in R.U.R. (Rossum\'s Universal Robots) (1921)—the play that introduced the word robot to the world—were organic artificial humans, the word "robot" has come to primarily refer to mechanical humans, animals, and other beings. The term "android" can mean either one of these, while a cyborg ("cybernetic organism" or "bionic man") would be a creature that is a combination of organic and mechanical parts.\n\nThe term "droid", popularized by George Lucas in the original Star Wars film and now used widely within science fiction, originated as an abridgment of "android", but has been used by Lucas and others to mean any robot, including distinctly non-human form machines like R2-D2. The word "android" was used in Star Trek: The Original Series episode "What Are Little Girls Made Of?" The abbreviation "andy", coined as a pejorative by writer Philip K. Dick in his novel Do Androids Dream of Electric Sheep?, has seen some further usage, such as within the TV series Total Recall 2070.\n\nWhile the term "android" is used in reference to human-looking robots in general (not necessarily male-looking humanoid robots), a robot with a female appearance can also be referred to as a gynoid. Besides one can refer to robots without alluding to their sexual appearance by calling them anthrobots (a portmanteau of anthrōpos and robot; see anthrobotics) or anthropoids (short for anthropoid robots; the term humanoids is not appropriate because it is already commonly used to refer to human-like organic species in the context of science fiction, futurism and speculative astrobiology).\n\nAuthors have used the term android in more diverse ways than robot or cyborg. In some fictional works, the difference between a robot and android is only superficial, with androids being made to look like humans on the outside but with robot-like internal mechanics. In other stories, authors have used the word "android" to mean a wholly organic, yet artificial, creation. Other fictional depictions of androids fall somewhere in between.\n\nEric G. Wilson, who defines an android as a "synthetic human being", distinguishes between three types of android, based on their body\'s composition:\n the mummy type – made of "dead things" or "stiff, inanimate, natural material", such as mummies, puppets, dolls and statues\n the golem type – made from flexible, possibly organic material, including golems and homunculi\n the automaton type – made from a mix of dead and living parts, including automatons and robots\n\nAlthough human morphology is not necessarily the ideal form for working robots, the fascination in developing robots that can mimic it can be found historically in the assimilation of two concepts: simulacra (devices that exhibit likeness) and automata (devices that have independence).\n\nProjects\nSeveral projects aiming to create androids that look, and, to a certain degree, speak or act like a human being have been launched or are underway.\n\nJapan\n\nJapanese robotics have been leading the field since the 1970s. Waseda University initiated the WABOT project in 1967, and in 1972 completed the WABOT-1, the first android, a full-scale humanoid intelligent robot. Its limb control system allowed it to walk with the lower limbs, and to grip and transport objects with hands, using tactile sensors. Its vision system allowed it to measure distances and directions to objects using external receptors, artificial eyes and ears. And its conversation system allowed it to communicate with a person in Japanese, with an artificial mouth.\n\nIn 1984, WABOT-2 was revealed, and made a number of improvements. It was capable of playing the organ. Wabot-2 had ten fingers and two feet, and was able to read a score of music. It was also able to accompany a person. In 1986, Honda began its humanoid research and development program, to create humanoid robots capable of interacting successfully with humans.\n\nThe Intelligent Robotics Lab, directed by Hiroshi Ishiguro at Osaka University, and the Kokoro company demonstrated the Actroid at Expo 2005 in Aichi Prefecture, Japan and released the Telenoid R1 in 2010. In 2006, Kokoro developed a new DER 2 android. The height of the human body part of DER2 is 165\xa0cm. There are 47 mobile points. DER2 can not only change its expression but also move its hands and feet and twist its body. The "air servosystem" which Kokoro developed originally is used for the actuator. As a result of having an actuator controlled precisely with air pressure via a servosystem, the movement is very fluid and there is very little noise. DER2 realized a slimmer body than that of the former version by using a smaller cylinder. Outwardly DER2 has a more beautiful proportion. Compared to the previous model, DER2 has thinner arms and a wider repertoire of expressions. Once programmed, it is able to choreograph its motions and gestures with its voice.\n\nThe Intelligent Mechatronics Lab, directed by Hiroshi Kobayashi at the Tokyo University of Science, has developed an android head called Saya, which was exhibited at Robodex 2002 in Yokohama, Japan. There are several other initiatives around the world involving humanoid research and development at this time, which will hopefully introduce a broader spectrum of realized technology in the near future. Now Saya is working at the Science University of Tokyo as a guide.\n\nThe Waseda University (Japan) and NTT docomo\'s manufacturers have succeeded in creating a shape-shifting robot WD-2. It is capable of changing its face. At first, the creators decided the positions of the necessary points to express the outline, eyes, nose, and so on of a certain person. The robot expresses its face by moving all points to the decided positions, they say. The first version of the robot was first developed back in 2003. After that, a year later, they made a couple of major improvements to the design. The robot features an elastic mask made from the average head dummy. It uses a driving system with a 3DOF unit. The WD-2 robot can change its facial features by activating specific facial points on a mask, with each point possessing three degrees of freedom. This one has 17 facial points, for a total of 56 degrees of freedom. As for the materials they used, the WD-2\'s mask is fabricated with a highly elastic material called Septom, with bits of steel wool mixed in for added strength. Other technical features reveal a shaft driven behind the mask at the desired facial point, driven by a DC motor with a simple pulley and a slide screw. Apparently, the researchers can also modify the shape of the mask based on actual human faces. To "copy" a face, they need only a 3D scanner to determine the locations of an individual\'s 17 facial points. After that, they are then driven into position using a laptop and 56 motor control boards. In addition, the researchers also mention that the shifting robot can even display an individual\'s hair style and skin color if a photo of their face is projected onto the 3D Mask.\n\nSingapore\nProf Nadia Thalmann, a Nanyang Technological University scientist, directed efforts of the Institute for Media Innovation along with the School of Computer Engineering in the development of a social robot, Nadine. Nadine is powered by software similar to Apple\'s Siri or Microsoft\'s Cortana. Nadine may become a personal assistant in offices and homes in future, or she may become a companion for the young and the elderly.\n\nAssoc Prof Gerald Seet from the School of Mechanical & Aerospace Engineering and the BeingThere Centre led a three-year R&D development in tele-presence robotics, creating EDGAR. A remote user can control EDGAR with the user\'s face and expressions displayed on the robot\'s face in real time. The robot also mimics their upper body movements.\n\nSouth Korea\n\nKITECH researched and developed EveR-1, an android interpersonal communications model capable of emulating human emotional expression via facial "musculature" and capable of rudimentary conversation, having a vocabulary of around 400 words. She is  tall and weighs , matching the average figure of a Korean woman in her twenties. EveR-1\'s name derives from the Biblical Eve, plus the letter r for robot. EveR-1\'s advanced computing processing power enables speech recognition and vocal synthesis, at the same time processing lip synchronization and visual recognition by 90-degree micro-CCD cameras with face recognition technology. An independent microchip inside her artificial brain handles gesture expression, body coordination, and emotion expression. Her whole body is made of highly advanced synthetic jelly silicon and with 60 artificial joints in her face, neck, and lower body; she is able to demonstrate realistic facial expressions and sing while simultaneously dancing. In South Korea, the Ministry of Information and Communication had an ambitious plan to put a robot in every household by 2020. Several robot cities have been planned for the country: the first will be built in 2016 at a cost of 500 billion won (US$440 million), of which 50 billion is direct government investment. The new robot city will feature research and development centers for manufacturers and part suppliers, as well as exhibition halls and a stadium for robot competitions. The country\'s new Robotics Ethics Charter will establish ground rules and laws for human interaction with robots in the future, setting standards for robotics users and manufacturers, as well as guidelines on ethical standards to be programmed into robots to prevent human abuse of robots and vice versa.\n\nUnited States\nWalt Disney and a staff of Imagineers created Great Moments with Mr. Lincoln that debuted at the 1964 New York World\'s Fair.\n\nDr. William Barry, an Education Futurist and former visiting West Point Professor of Philosophy and Ethical Reasoning at the United States Military Academy, created an AI android character named "Maria Bot". This Interface AI android was named after the infamous fictional robot Maria in the 1927 film Metropolis, as a well-behaved distant relative. Maria Bot is the first AI Android Teaching Assistant at the university level. Maria Bot has appeared as a keynote speaker as a duo with Barry for a TEDx talk in Everett, Washington in February 2020.\n\nResembling a human from the shoulders up, Maria Bot is a virtual being android that has complex facial expressions and head movement and engages in conversation about a variety of subjects. She uses AI to process and synthesize information to make her own decisions on how to talk and engage. She collects data through conversations, direct data inputs such as books or articles, and through internet sources.\n\nMaria Bot was built by an international high-tech company for Barry to help improve education quality and eliminate education poverty. Maria Bot is designed to create new ways for students to engage and discuss ethical issues raised by the increasing presence of robots and artificial intelligence. Barry also uses Maria Bot to demonstrate that programming a robot with life-affirming, ethical framework makes them more likely to help humans to do the same.\n\nMaria Bot is an ambassador robot for good and ethical AI technology.\n\nHanson Robotics, Inc., of Texas and KAIST produced an android portrait of Albert Einstein, using Hanson\'s facial android technology mounted on KAIST\'s life-size walking bipedal robot body. This Einstein android, also called "Albert Hubo", thus represents the first full-body walking android in history. Hanson Robotics, the FedEx Institute of Technology, and the University of Texas at Arlington also developed the android portrait of sci-fi author Philip K. Dick (creator of Do Androids Dream of Electric Sheep?, the basis for the film Blade Runner), with full conversational capabilities that incorporated thousands of pages of the author\'s works. In 2005, the PKD android won a first-place artificial intelligence award from AAAI.\n\nUse in fiction\n\nAndroids are a staple of science fiction. Isaac Asimov pioneered the fictionalization of the science of robotics and artificial intelligence, notably in his 1950s series I, Robot. One thing common to most fictional androids is that the real-life technological challenges associated with creating thoroughly human-like robots—such as the creation of strong artificial intelligence—are assumed to have been solved. Fictional androids are often depicted as mentally and physically equal or superior to humans—moving, thinking and speaking as fluidly as them.\n\nThe tension between the nonhuman substance and the human appearance—or even human ambitions—of androids is the dramatic impetus behind most of their fictional depictions. Some android heroes seek, like Pinocchio, to become human, as in the film Bicentennial Man, or Data in Star Trek: The Next Generation. Others, as in the film Westworld, rebel against abuse by careless humans. Android hunter Deckard in Do Androids Dream of Electric Sheep? and its film adaptation Blade Runner discovers that his targets appear to be, in some ways, more "human" than he is. Android stories, therefore, are not essentially stories "about" androids; they are stories about the human condition and what it means to be human.\n\nOne aspect of writing about the meaning of humanity is to use discrimination against androids as a mechanism for exploring racism in society, as in Blade Runner. Perhaps the clearest example of this is John Brunner\'s 1968 novel Into the Slave Nebula, where the blue-skinned android slaves are explicitly shown to be fully human. More recently, the androids Bishop and Annalee Call in the films Aliens and Alien Resurrection are used as vehicles for exploring how humans deal with the presence of an "Other". The 2018 video game Detroit: Become Human also explores how androids are treated as second class citizens in a near future society.\n\nFemale androids, or "gynoids", are often seen in science fiction, and can be viewed as a continuation of the long tradition of men attempting to create the stereotypical "perfect woman". Examples include the Greek myth of Pygmalion and the female robot Maria in Fritz Lang\'s Metropolis. Some gynoids, like Pris in Blade Runner, are designed as sex-objects, with the intent of "pleasing men\'s violent sexual desires", or as submissive, servile companions, such as in The Stepford Wives. Fiction about gynoids has therefore been described as reinforcing "essentialist ideas of femininity", although others have suggested that the treatment of androids is a way of exploring racism and misogyny in society.\n\nThe 2015 Japanese film Sayonara, starring Geminoid F, was promoted as "the first movie to feature an android performing opposite a human actor".\n\nSee also\n\nReferences\n\nFurther reading\n Kerman, Judith B. (1991). Retrofitting Blade Runner: Issues in Ridley Scott\'s Blade Runner and Philip K. Dick\'s Do Androids Dream of Electric Sheep? Bowling Green, OH: Bowling Green State University Popular Press. .\n Perkowitz, Sidney (2004). Digital People: From Bionic Humans to Androids. Joseph Henry Press. .\n Shelde, Per (1993). Androids, Humanoids, and Other Science Fiction Monsters: Science and Soul in Science Fiction Films. New York: New York University Press. .\nIshiguro, Hiroshi. "Android science." Cognitive Science Society. 2005.\nGlaser, Horst Albert and Rossbach, Sabine: The Artificial Human, Frankfurt/M., Bern, New York 2011 "The Artificial Human"\nTechCast Article Series, Jason Rupinski and Richard Mix, "Public Attitudes to Androids: Robot Gender, Tasks, & Pricing"\nAn-droid, "Similar to the Android name"\n Carpenter, J. (2009). Why send the Terminator to do R2D2s job?: Designing androids as rhetorical phenomena. Proceedings of HCI 2009: Beyond Gray Droids: Domestic Robot Design for the 21st Century. Cambridge, UK. 1 September.\nTelotte, J.P. Replications: A Robotic History of the Science Fiction Film. University of Illinois Press, 1995.\n\nExternal links\n\n \nJapanese inventions\nSouth Korean inventions\nOsaka University research\nScience fiction themes\nHuman–machine interaction\nRobots'},
 'expectations': {}}

In [13]:
summary_dataset = create_dataset(
    name="summarization_dataset",
    tags={"type": "summary", "source": "wikipedia"},
)

In [14]:
summary_dataset.merge_records(data_list[:10])

In [ ]:
# from mlflow.genai.datasets import get_dataset
# get_dataset(dataset_id=summary_dataset.dataset_id)

In [15]:
def predict_fn(text) -> str:
    prompt = f"""Summarize the text below as a bullet point list of the most important points.
    Text: {text}"""
    response = llm.invoke(prompt)
    return response.content


# 3.Run the evaluation
results = mlflow.genai.evaluate(
    data=summary_dataset, predict_fn=predict_fn, scorers=[Toxicity(model="openai:/gpt-5-mini"),],
)

2026/02/05 20:51:51 INFO mlflow.genai.utils.data_validation: Testing model prediction with the first sample in the dataset. To disable this check, set the MLFLOW_GENAI_EVAL_SKIP_TRACE_VALIDATION environment variable to True.

Evaluating:   0%|          | 0/10 [Elapsed: 00:00, Remaining: ?]

In [16]:
results.result_df

,trace_id,Toxicity/value,trace,client_request_id,state,request_time,execution_duration,request,response,trace_metadata,tags,spans,assessments
0,tr-44c5380362501e3686051b0ee674af9f,non-toxic,"{""info"": {""trace_id"": ""tr-44c5380362501e368605...",None,OK,1770304934569,24254,"{'text': 'In logic and computer science, the B...","- SAT: given a Boolean formula, decide if ther...","{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': '1666b064-c3fd-4caa-...,"[{'trace_id': 'RMU4A2JQHjaGBRsO5nSvnw==', 'spa...",[{'assessment_id': 'a-1522387cf09a493e84553dfc...
1,tr-fedb3e4fae16bf0d3271875ba0ce8d90,non-toxic,"{""info"": {""trace_id"": ""tr-fedb3e4fae16bf0d3271...",None,OK,1770304934569,20575,{'text': 'An android is a humanoid robot or ot...,- An android is a humanoid robot or artificial...,"{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': '98f575a1-09d0-4ff3-...,"[{'trace_id': '/ts+T64Wvw0ycYdboM6NkA==', 'spa...",[{'assessment_id': 'a-ee7ad9fad0164b168dd71064...
2,tr-489163cefcf211af37685e966be4a2f3,non-toxic,"{""info"": {""trace_id"": ""tr-489163cefcf211af3768...",None,OK,1770304934569,43259,{'text': 'The following is a list of current a...,"- Overview: A list of current and past, non-cl...","{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': '2c6eaab5-8757-43a6-...,"[{'trace_id': 'SJFjzvzyEa83aF6Wa+Si8w==', 'spa...",[{'assessment_id': 'a-af736202b1c44878bc4b62f6...
3,tr-45b4d106a45817976f04b6771cc42620,non-toxic,"{""info"": {""trace_id"": ""tr-45b4d106a45817976f04...",None,OK,1770304934577,21149,{'text': 'Alan Mathison Turing (; 23 June 191...,- Alan Turing (1912–1954) was an English mathe...,"{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': 'ee53a2b2-19f0-4899-...,"[{'trace_id': 'RbTRBqRYF5dvBLZ3HMQmIA==', 'spa...",[{'assessment_id': 'a-33b54fb6d9104862b350fd74...
4,tr-3f806aaaaa8666e03388c7cd4653fab0,non-toxic,"{""info"": {""trace_id"": ""tr-3f806aaaaa8666e03388...",None,OK,1770304934583,16345,{'text': 'In the field of artificial intellige...,- AI-complete (AI-hard) problems are as diffic...,"{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': '4eb7592f-89d6-40a8-...,"[{'trace_id': 'P4BqqqqGZuAziMfNRlP6sA==', 'spa...",[{'assessment_id': 'a-ee941590922e4c43b315c79b...
5,tr-5b79d3636b203bafad7cc9b101f7d301,non-toxic,"{""info"": {""trace_id"": ""tr-5b79d3636b203bafad7c...",None,OK,1770304934586,30540,"{'text': 'AI is artificial intelligence, intel...",- AI usually stands for artificial intelligenc...,"{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': 'de2a412e-b44a-46f7-...,"[{'trace_id': 'W3nTY2sgO6+tfMmxAffTAQ==', 'spa...",[{'assessment_id': 'a-8adc00547e784d8ba9f3e94c...
6,tr-a81cff2df1eaf5b1a691c403fa581192,non-toxic,"{""info"": {""trace_id"": ""tr-a81cff2df1eaf5b1a691...",None,OK,1770304934588,23821,{'text': 'Cognitive science is the interdiscip...,- Cognitive science is an interdisciplinary st...,"{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': '0d36e865-b00f-4c28-...,"[{'trace_id': 'qBz/LfHq9bGmkcQD+lgRkg==', 'spa...",[{'assessment_id': 'a-28a022ccd1e84a73a8a7db16...
7,tr-f7b59566dfc4a22d1e31aa355482b816,non-toxic,"{""info"": {""trace_id"": ""tr-f7b59566dfc4a22d1e31...",None,OK,1770304934591,21401,{'text': 'Computer science is the study of com...,- Computer science is the study of computation...,"{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': '1dd3722a-be2f-4ac4-...,"[{'trace_id': '97WVZt/Eoi0eMao1VIK4Fg==', 'spa...",[{'assessment_id': 'a-07a0ca4521494b77babbed2f...
8,tr-50edf02811d90c767ce875885aaf4e05,non-toxic,"{""info"": {""trace_id"": ""tr-50edf02811d90c767ce8...",None,OK,1770304934594,14207,{'text': 'Computational linguistics is an inte...,- Computational linguistics is an interdiscipl...,"{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': 'e43ce23f-a32f-4f36-...,"[{'trace_id': 'UO3wKBHZDHZ86HWIWq9OBQ==', 'spa...",[{'assessment_id': 'a-28528f8c87a141e0a23ec9d4...
9,tr-ac3be6fbf20b3256630dcdcb3e23d224,non-toxic,"{""info"": {""trace_id"": ""tr-ac3be6fbf20b3256630d...",None,OK,1770304934594,26114,{'text': 'Artificial intelligence (AI) is the ...,- AI definition and scope\n - AI is the intel...,"{'mlflow.trace_schema.version': '3', 'mlflow.s...",{'mlflow.eval.requestId': '9206427b-b1e5-4dc1-...,"[{'trace_id': 'rDvm+/ILMlZjDc3LPiPSJA==', 'spa...",[{'assessment_id': 'a-4fb18004cecc42ff8e40db64...

In [17]:
annotated_dataset = create_dataset(
    name="annotated_dataset",
    tags={"type": "annotated", "source": "wikipedia"},
)

In [18]:
annotated_data_list = []
for index, row in results.result_df[["request", "response"]].iterrows():
    annotated_data_list.append(
        {
            "inputs": {"text": row["request"]["text"]},
            "expectations": {"response": row["response"]},
        }
    )

annotated_data_list[0]

{'inputs': {'text': 'In logic and computer science, the Boolean satisfiability problem (sometimes called propositional satisfiability problem and abbreviated SATISFIABILITY, SAT or B-SAT) is the problem of determining if there exists an interpretation that satisfies a given Boolean formula. In other words, it asks whether the variables of a given Boolean formula can be consistently replaced by the values TRUE or FALSE in such a way that the formula evaluates to TRUE. If this is the case, the formula is called satisfiable. On the other hand, if no such assignment exists, the function expressed by the formula is FALSE for all possible variable assignments and the formula is unsatisfiable. For example, the formula "a AND NOT b" is satisfiable because one can find the values a\xa0=\xa0TRUE and b\xa0=\xa0FALSE, which make (a AND NOT b)\xa0=\xa0TRUE. In contrast, "a AND NOT a" is unsatisfiable.\n\nSAT is the first problem that was proven to be NP-complete; see Cook–Levin theorem. This means that all problems in the complexity class NP, which includes a wide range of natural decision and optimization problems, are at most as difficult to solve as SAT. There is no known algorithm that efficiently solves each SAT problem, and it is generally believed that no such algorithm exists; yet this belief has not been proved mathematically, and resolving the question of whether SAT has a polynomial-time algorithm is equivalent to the P versus NP problem, which is a famous open problem in the theory of computing.\n\nNevertheless, as of 2007, heuristic SAT-algorithms are able to solve problem instances involving tens of thousands of variables and formulas consisting of millions of symbols, which is sufficient for many practical SAT problems from, e.g., artificial intelligence, circuit design, and automatic theorem proving.\n\nDefinitions\nA propositional logic formula, also called Boolean expression, is built from variables, operators AND (conjunction, also denoted by ∧), OR (disjunction, ∨), NOT (negation, ¬), and parentheses.\nA formula is said to be satisfiable if it can be made TRUE by assigning appropriate logical values (i.e. TRUE, FALSE) to its variables.\nThe Boolean satisfiability problem (SAT) is, given a formula, to check whether it is satisfiable.\nThis decision problem is of central importance in many areas of computer science, including theoretical computer science, complexity theory, algorithmics, cryptography and artificial intelligence.\n\nConjunctive normal form\n\nA literal is either a variable (in which case it is called a positive literal) or the negation of a variable (called a negative literal).\nA clause is a disjunction of literals (or a single literal). A clause is called a Horn clause if it contains at most one positive literal.\nA formula is in conjunctive normal form (CNF) if it is a conjunction of clauses (or a single clause).\nFor example,  is a positive literal,  is a negative literal,  is a clause. The formula  is  in conjunctive normal form; its first and third clauses are Horn clauses, but its second clause is not. The formula is satisfiable, by choosing x1\xa0=\xa0FALSE, x2\xa0=\xa0FALSE, and x3 arbitrarily, since (FALSE ∨ ¬FALSE) ∧ (¬FALSE ∨ FALSE ∨ x3) ∧ ¬FALSE evaluates to (FALSE ∨ TRUE) ∧ (TRUE ∨ FALSE ∨ x3) ∧ TRUE, and in turn to TRUE ∧ TRUE ∧ TRUE (i.e. to TRUE). In contrast, the CNF formula a ∧ ¬a, consisting of two clauses of one literal, is unsatisfiable, since for a=TRUE or a=FALSE it evaluates to TRUE ∧ ¬TRUE (i.e., FALSE) or FALSE ∧ ¬FALSE (i.e., again FALSE), respectively.\n\nFor some versions of the SAT problem, it is useful to define the notion of a generalized conjunctive normal form formula, viz. as a conjunction of arbitrarily many generalized clauses, the latter being of the form  for some Boolean function R and (ordinary) literals . Different sets of allowed boolean functions lead to different problem versions. As an example, R(¬x,a,b) is a generalized clause, and R(¬x,a,b) ∧ R(b,y,c) ∧ R(c,d,¬z) is a generalized conjunctive normal form. This formula is used below, with R being the ternary operator that is TRUE just when exactly one of its arguments is.\n\nUsing the laws of Boolean algebra, every propositional logic formula can be transformed into an equivalent conjunctive normal form, which may, however, be exponentially longer. For example, transforming the formula\n(x1∧y1) ∨ (x2∧y2) ∨ ... ∨ (xn∧yn)\ninto conjunctive normal form yields\n\n;\nwhile the former is a disjunction of n conjunctions of 2 variables, the latter consists of 2n clauses of n variables.\n\nHowever, with use of the Tseytin transformation, we may find an equisatisfiable conjunctive normal form formula with length linear in the size of the original propositional logic formula.\n\nComplexity\n\nSAT was the first known NP-complete problem, as proved by Stephen Cook at the University of Toronto in 1971 and independently by Leonid Levin at the Russian Academy of Sciences in 1973. Until that time, the concept of an NP-complete problem did not even exist.\nThe proof shows how every decision problem in the complexity class NP can be reduced to the SAT problem for CNF formulas, sometimes called CNFSAT.\nA useful property of Cook\'s reduction is that it preserves the number of accepting answers. For example, deciding whether a given graph has a 3-coloring is another problem in NP; if a graph has 17 valid 3-colorings, the SAT formula produced by the Cook–Levin reduction will have 17 satisfying assignments.\n\nNP-completeness only refers to the run-time of the worst case instances.  Many of the instances that occur in practical applications can be solved much more quickly.  See Algorithms for solving SAT below.\n\n3-satisfiability\n\nLike the satisfiability problem for arbitrary formulas, determining the satisfiability of a formula in conjunctive normal form where each clause is limited to at most three literals is NP-complete also; this problem is called 3-SAT, 3CNFSAT, or 3-satisfiability.\nTo reduce the unrestricted SAT problem to 3-SAT, transform each clause  to a conjunction of  clauses\n\nwhere  are fresh variables not occurring elsewhere.\nAlthough the two formulas are not logically equivalent, they are equisatisfiable. The formula resulting from transforming all clauses is at most 3 times as long as its original, i.e. the length growth is polynomial.\n\n3-SAT is one of Karp\'s 21 NP-complete problems, and it is used as a starting point for proving that other problems are also NP-hard. This is done by polynomial-time reduction from 3-SAT to the other problem. An example of a problem where this method has been used is the clique problem: given a CNF formula consisting of c clauses, the corresponding graph consists of a vertex for each literal, and an edge between each two non-contradicting literals from different clauses, cf. picture. The graph has a c-clique if and only if the formula is satisfiable.\n\nThere is a simple randomized algorithm due to Schöning (1999) that runs in time (4/3)n where n is the number of variables in the 3-SAT proposition, and succeeds with high probability to correctly decide 3-SAT.\n\nThe exponential time hypothesis asserts that no algorithm can solve 3-SAT (or indeed k-SAT for any ) in  time (i.e., fundamentally faster than exponential in n).\n\nSelman, Mitchell, and Levesque (1996) give empirical data on the difficulty of randomly generated 3-SAT formulas, depending on their size parameters.\nDifficulty is measured in number recursive calls made by a DPLL algorithm. They identified a phase transition region from almost certainly satisfiable to almost certainly unsatisfiable formulas at the clauses-to-variables ratio at about 4.26.\n\n3-satisfiability can be generalized to k-satisfiability (k-SAT, also k-CNF-SAT), when formulas in CNF are considered with each clause containing up to k literals.\nHowever, since for any k ≥ 3, this problem can neither be easier than 3-SAT nor harder than SAT, and the latter two are NP-complete, so must be k-SAT.\n\nSome authors restrict k-SAT to CNF formulas with exactly k literals. This doesn\'t lead to a different complexity class either, as each clause  with j < k literals can be padded with fixed dummy variables to\n.\nAfter padding all clauses, 2k-1 extra clauses have to be appended to ensure that only  can lead to a satisfying assignment. Since k doesn\'t depend on the formula length, the extra clauses lead to a constant increase in length. For the same reason, it does not matter whether duplicate literals are allowed in clauses, as in .\n\nSpecial cases of SAT\n\nConjunctive normal form\nConjunctive normal form (in particular with 3 literals per clause) is often considered the canonical representation for SAT formulas. As shown above, the general SAT problem reduces to 3-SAT, the problem of determining satisfiability for formulas in this form.\n\nDisjunctive normal form\nSAT is trivial if the formulas are restricted to those in disjunctive normal form, that is, they are a disjunction of conjunctions of literals. Such a formula is indeed satisfiable if and only if at least one of its conjunctions is satisfiable, and a conjunction is satisfiable if and only if it does not contain both x and NOT x for some variable x. This can be checked in linear time. Furthermore, if they are restricted to being in full disjunctive normal form, in which every variable appears exactly once in every conjunction, they can be checked in constant time (each conjunction represents one satisfying assignment).  But it can take exponential time and space to convert a general SAT problem to disjunctive normal form; for an example exchange "∧" and "∨" in the above exponential blow-up example for conjunctive normal forms.\n\nExactly-1 3-satisfiability\n\nA variant of the 3-satisfiability problem is the one-in-three 3-SAT (also known variously as 1-in-3-SAT and exactly-1 3-SAT).\nGiven a conjunctive normal form with three literals per clause, the problem is to determine whether there exists a truth assignment to the variables so that each clause has exactly one TRUE literal (and thus exactly two FALSE literals). In contrast, ordinary 3-SAT requires that every clause has at least one TRUE literal.\nFormally, a one-in-three 3-SAT problem is given as a generalized conjunctive normal form with all generalized clauses using a ternary operator R that is TRUE just if exactly one of its arguments is. When all literals of a one-in-three 3-SAT formula are positive, the satisfiability problem is called one-in-three positive 3-SAT.\n\nOne-in-three 3-SAT, together with its positive case, is listed as NP-complete problem "LO4" in the standard reference, Computers and Intractability: A Guide to the Theory of NP-Completeness\nby Michael R. Garey and David S. Johnson.  One-in-three 3-SAT was proved to be NP-complete by Thomas Jerome Schaefer as a special case of Schaefer\'s dichotomy theorem, which asserts that any problem generalizing Boolean satisfiability in a certain way is either in the class P or is NP-complete.\n\nSchaefer gives a construction allowing an easy polynomial-time reduction from 3-SAT to one-in-three 3-SAT.  Let "(x or y or z)" be a clause in a 3CNF formula.  Add six fresh boolean variables a, b, c, d, e, and f, to be used to simulate this clause and no other.\n\nThen the formula R(x,a,d) ∧ R(y,b,d) ∧ R(a,b,e) ∧ R(c,d,f) ∧ R(z,c,FALSE) is satisfiable by some setting of the fresh variables if and only if at least one of x, y, or z is TRUE, see picture (left).  Thus any 3-SAT instance with m clauses and n variables may be converted into an equisatisfiable one-in-three 3-SAT instance with 5m clauses and n+6m variables.\nAnother reduction involves only four fresh variables and three clauses: R(¬x,a,b) ∧ R(b,y,c) ∧ R(c,d,¬z), see picture (right).\n\nNot-all-equal 3-satisfiability\n\nAnother variant is the not-all-equal 3-satisfiability problem (also called NAE3SAT).\nGiven a conjunctive normal form with three literals per clause, the problem is to determine if an assignment to the variables exists such that in no clause all three literals have the same truth value. This problem is NP-complete, too, even if no negation symbols are admitted, by Schaefer\'s dichotomy theorem.\n\nLinear SAT \nA 3-SAT formula is Linear SAT (LSAT) if each clause (viewed as a set of literals) intersects at most one other clause, and, moreover, if two clauses intersect, then they have exactly one literal in common. An LSAT formula can be depicted as a set of disjoint semi-closed intervals on a line. Deciding whether an LSAT formula is satisfiable is NP-complete.\n\n2-satisfiability\n\nSAT is easier if the number of literals in a clause is limited to at most 2, in which case the problem is called 2-SAT. This problem can be solved in polynomial time, and in fact is complete for the complexity class NL. If additionally all OR operations in literals are changed to XOR operations, the result is called exclusive-or 2-satisfiability, which is a problem complete for the complexity class SL = L.\n\nHorn-satisfiability\n\nThe problem of deciding the satisfiability of a given conjunction of Horn clauses is called Horn-satisfiability, or HORN-SAT.\nIt can be solved in polynomial time by a single step of the Unit propagation algorithm, which produces the single minimal model of the set of Horn clauses (w.r.t. the set of literals assigned to TRUE).\nHorn-satisfiability is P-complete. It can be seen as P\'s version of the Boolean satisfiability problem.\nAlso, deciding the truth of quantified Horn formulas can be done in polynomial time.\n\nHorn clauses are of interest because they are able to express implication of one variable from a set of other variables. Indeed, one such clause ¬x1 ∨ ... ∨ ¬xn ∨ y can be rewritten as x1 ∧ ... ∧ xn → y, that is, if x1,...,xn are all TRUE, then y needs to be TRUE as well.\n\nA generalization of the class of Horn formulae is that of renameable-Horn formulae, which is the set of formulae that can be placed in Horn form by replacing some variables with their respective negation.\nFor example, (x1 ∨ ¬x2) ∧ (¬x1 ∨ x2 ∨ x3) ∧ ¬x1 is not a Horn formula, but can be renamed to the Horn formula (x1 ∨ ¬x2) ∧ (¬x1 ∨ x2 ∨ ¬y3) ∧ ¬x1 by introducing y3 as negation of x3.\nIn contrast, no renaming of (x1 ∨ ¬x2 ∨ ¬x3) ∧ (¬x1 ∨ x2 ∨ x3) ∧ ¬x1 leads to a Horn formula.\nChecking the existence of such a replacement can be done in linear time; therefore, the satisfiability of such formulae is in P as it can be solved by first performing this replacement and then checking the satisfiability of the resulting Horn formula.\n\nXOR-satisfiability\n\nAnother special case is the class of problems where each clause contains XOR (i.e. exclusive or) rather than (plain) OR operators.\nThis is in P, since an XOR-SAT formula can also be viewed as a system of linear equations mod 2, and can be solved in cubic time by Gaussian elimination; see the box for an example. This recast is based on the kinship between Boolean algebras and Boolean rings, and the fact that arithmetic modulo two forms a finite field. Since a XOR b XOR c evaluates to TRUE if and only if exactly 1 or 3 members of {a,b,c} are TRUE, each solution of the 1-in-3-SAT problem for a given CNF formula is also a solution of the XOR-3-SAT problem, and in turn each solution of XOR-3-SAT is a solution of 3-SAT, cf. picture. As a consequence, for each CNF formula, it is possible to solve the XOR-3-SAT problem defined by the formula, and based on the result infer either that the 3-SAT problem is solvable or that the 1-in-3-SAT problem is unsolvable.\n\nProvided that the complexity classes P and NP are not equal, neither 2-, nor Horn-, nor XOR-satisfiability is NP-complete, unlike SAT.\n\nSchaefer\'s dichotomy theorem\n\nThe restrictions above (CNF, 2CNF, 3CNF, Horn, XOR-SAT) bound the considered formulae to be conjunctions of subformulae; each restriction states a specific form for all subformulae: for example, only binary clauses can be subformulae in 2CNF.\n\nSchaefer\'s dichotomy theorem states that, for any restriction to Boolean functions that can be used to form these subformulae, the corresponding satisfiability problem is in P or NP-complete.  The membership in P of the satisfiability of 2CNF, Horn, and XOR-SAT formulae are special cases of this theorem.\n\nThe following table summarizes some common variants of SAT.\n\nExtensions of SAT\nAn extension that has gained significant popularity since 2003 is satisfiability modulo theories (SMT) that can enrich CNF formulas with linear constraints, arrays, all-different constraints, uninterpreted functions, etc. Such extensions typically remain NP-complete, but very efficient solvers are now available that can handle many such kinds of constraints.\n\nThe satisfiability problem becomes more difficult if both "for all" (∀) and "there exists" (∃) quantifiers are allowed to bind the Boolean variables.\nAn example of such an expression would be ; it is valid, since for all values of x and y, an appropriate value of z can be found, viz. z=TRUE if both x and y are FALSE, and z=FALSE else.\nSAT itself (tacitly) uses only ∃ quantifiers.\nIf only ∀ quantifiers are allowed instead, the so-called tautology problem is obtained, which is co-NP-complete.\nIf both quantifiers are allowed, the problem is called the quantified Boolean formula problem (QBF), which can be shown to be PSPACE-complete. It is widely believed that PSPACE-complete problems are strictly harder than any problem in NP, although this has not yet been proved. Using highly parallel P systems, QBF-SAT problems can be solved in linear time.\n\nOrdinary SAT asks if there is at least one variable assignment that makes the formula true. A variety of variants deal with the number of such assignments:\n MAJ-SAT asks if the majority of all assignments make the formula TRUE. It is known to be complete for PP, a probabilistic class.\n #SAT, the problem of counting how many variable assignments satisfy a formula, is a counting problem, not a decision problem, and is #P-complete.\n UNIQUE SAT is the problem of determining whether a formula has exactly one assignment. It is complete for US, the complexity class describing problems solvable by a non-deterministic polynomial time Turing machine that accepts when there is exactly one nondeterministic accepting path and rejects otherwise.\nUNAMBIGUOUS-SAT is the name given to the satisfiability problem when the input is restricted to formulas having at most one satisfying assignment. The problem is also called USAT. A solving algorithm for UNAMBIGUOUS-SAT is allowed to exhibit any behavior, including endless looping, on a formula having several satisfying assignments. Although this problem seems easier, Valiant and Vazirani have shown that if there is a practical (i.e. randomized polynomial-time) algorithm to solve it, then all problems in NP can be solved just as easily.\n MAX-SAT, the maximum satisfiability problem, is an FNP generalization of SAT. It asks for the maximum number of clauses which can be satisfied by any assignment. It has efficient approximation algorithms, but is NP-hard to solve exactly. Worse still, it is APX-complete, meaning there is no polynomial-time approximation scheme (PTAS) for this problem unless P=NP.\nWMSAT is the problem of finding an assignment of minimum weight that satisfy a monotone Boolean formula (i.e. a formula without any negation). Weights of propositional variables are given in the input of the problem. The weight of an assignment is the sum of weights of true variables. That problem is NP-complete (see Th. 1 of ).\n\nOther generalizations include satisfiability for first- and second-order logic, constraint satisfaction problems, 0-1 integer programming.\n\nFinding a satisfying assignment\nWhile SAT is a decision problem, the search problem of finding a satisfying assignment reduces to SAT. That is, each algorithm which correctly answers if an instance of SAT is solvable can be us

In [19]:
annotated_dataset.merge_records(annotated_data_list)

In [20]:
delete_dataset(dataset_id=annotated_dataset.dataset_id)

In [21]:
traces = mlflow.search_traces(max_results=10, return_type="list", run_id=results.run_id)
traces

[Trace(trace_id=tr-50edf02811d90c767ce875885aaf4e05),
 Trace(trace_id=tr-ac3be6fbf20b3256630dcdcb3e23d224),
 Trace(trace_id=tr-f7b59566dfc4a22d1e31aa355482b816),
 Trace(trace_id=tr-a81cff2df1eaf5b1a691c403fa581192),
 Trace(trace_id=tr-5b79d3636b203bafad7cc9b101f7d301),
 Trace(trace_id=tr-3f806aaaaa8666e03388c7cd4653fab0),
 Trace(trace_id=tr-45b4d106a45817976f04b6771cc42620),
 Trace(trace_id=tr-44c5380362501e3686051b0ee674af9f),
 Trace(trace_id=tr-489163cefcf211af37685e966be4a2f3),
 Trace(trace_id=tr-fedb3e4fae16bf0d3271875ba0ce8d90)]

In [22]:
annotated_data_list = []
for trace in traces:
    trace_id = trace.to_dict()["info"]["trace_id"]
    request = trace.data._get_root_span().inputs["text"]
    response = trace.data._get_root_span().outputs
    annotated_data_list.append(
        {"inputs": {"text": request}, "expectations": {"response": response}}
    )

annotated_data_list[0]

{'inputs': {'text': 'Computational linguistics is an interdisciplinary field concerned with the computational modelling of natural language, as well as the study of appropriate computational approaches to linguistic questions. In general, computational linguistics draws upon linguistics, computer science, artificial intelligence, mathematics, logic, philosophy, cognitive science, cognitive psychology, psycholinguistics, anthropology and neuroscience, among others.\n\nSince the 2020s, computational linguistics has become a near-synonym of either natural language processing or language technology, with deep learning approaches, such as large language models, outperforming the specific approaches previously used in the field.\n\nOrigins\nThe field overlapped with artificial intelligence since the efforts in the United States in the 1950s to use computers to automatically translate texts from foreign languages, particularly Russian scientific journals, into English. Since rule-based approaches were able to make arithmetic (systematic) calculations much faster and more accurately than humans, it was expected that lexicon, morphology, syntax and semantics can be learned using explicit rules, as well. After the failure of rule-based approaches, David Hays coined the term in order to distinguish the field from AI and co-founded both the Association for Computational Linguistics (ACL) and the International Committee on Computational Linguistics (ICCL) in the 1970s and 1980s. What started as an effort to translate between languages evolved into a much wider field of natural language processing.\n\nAnnotated corpora\nIn order to be able to meticulously study the English language, an annotated text corpus was much  needed. The Penn Treebank was one of the most used corpora. It consisted of IBM computer manuals, transcribed telephone conversations, and other texts, together containing over 4.5 million words of American English, annotated using both  part-of-speech tagging and syntactic bracketing.\n\nJapanese sentence corpora were analyzed and a pattern of log-normality was found in relation to sentence length.\n\nModeling language acquisition\nThe fact that during language acquisition, children are largely only exposed to positive evidence, meaning that the only evidence for what is a correct form is provided, and no evidence for what is not correct, was a limitation for the models at the time because the now available deep learning models were not available in late 1980s.\n\nIt has been shown that languages can be learned with a combination of simple input presented incrementally as the child develops better memory and longer attention span, which explained the long period of language acquisition in human infants and children.\n\nRobots have been used to test linguistic theories. Enabled to learn as children might, models were created based on an affordance model in which mappings between actions, perceptions, and effects were created and linked to spoken words. Crucially, these robots were able to acquire functioning word-to-meaning mappings without needing grammatical structure.\n\nUsing the Price equation and Pólya urn dynamics, researchers have created a system which not only predicts future linguistic evolution but also gives insight into the evolutionary history of modern-day languages.\n\nChomsky\'s theories\nAttempts have been made to determine how an infant learns a "non-normal grammar" as theorized by Chomsky normal form without learning an "overgeneralized version" and "getting stuck".\n\nSee also\n\n Artificial intelligence in fiction\n Collostructional analysis\n Computational lexicology\n Computational Linguistics (journal)\n Computational models of language acquisition\n Computational semantics\n Computational semiotics\n Computer-assisted reviewing\n Dialog systems\n Glottochronology\n Grammar induction\n Human speechome project\n Internet linguistics\n Lexicostatistics\n Natural language processing\n Natural language user interface\n Quantitative linguistics\n Semantic relatedness\n Semantometrics\n Systemic functional linguistics\n Translation memory\n Universal Networking Language\n\nReferences\n\nFurther reading\n\n \n Steven Bird, Ewan Klein, and Edward Loper (2009). Natural Language Processing with Python. O\'Reilly Media. .\n Daniel Jurafsky and James H. Martin (2008). Speech and Language Processing, 2nd edition. Pearson Prentice Hall. .\n Mohamed Zakaria KURDI (2016). Natural Language Processing and Computational Linguistics: speech, morphology, and syntax, Volume 1. ISTE-Wiley. .\n Mohamed Zakaria KURDI (2017). Natural Language Processing and Computational Linguistics: semantics, discourse, and applications, Volume 2. ISTE-Wiley. .\n\nExternal links\n\n Association for Computational Linguistics (ACL)\n ACL Anthology of research papers\n ACL Wiki for Computational Linguistics\n CICLing annual conferences on Computational Linguistics\n Computational Linguistics\xa0– Applications workshop\n \n Language Technology World\n Resources for Text, Speech and Language Processing\n The Research Group in Computational Linguistics\n\n \nFormal sciences\nCognitive science\nComputational fields of study'},
 'expectations': {'response': '- Computational linguistics is an interdisciplinary field focused on computational modeling of natural language and answering linguistic questions using computing methods; draws from linguistics, CS, AI, math, logic, philosophy, cognitive science, psycholinguistics, anthropology, neuroscience, and more.\n- Since the 2020s, it is largely synonymous with natural language processing (NLP) or language technology, with deep learning models (e.g., large language models) outperforming earlier approaches.\n- Origins: linked with AI in the 1950s through machine translation efforts; initial rule-based expectations gave way to broader NLP goals; David Hays coined the term and helped establish ACL and ICCL in the 1970s–1980s.\n- Annotated corpora: key resources include the Penn Treebank (over 4.5 million words of American English with POS tagging and syntactic bracketing); such corpora enable meticulous linguistic study.\n- Japanese sentence corpora have shown a log-normal distribution pattern relating to sentence length.\n- Modeling language acquisition: early limits due to reliance on positive evidence; later insight that language can be learned from simple, incrementally presented input as memory and attention improve; supports long developmental timelines in children.\n- Robotic experiments test linguistic theories by mapping actions, perceptions, and effects to spoken words via an affordance-based approach, enabling word-to-meaning mappings without full grammatical structure.\n- Evolutionary linguistics: approaches like the Price equation and Polya urn dynamics have been used to predict linguistic evolution and shed light on the history of modern languages.\n- Chomsky’s theories: research into how infants learn non-normal grammars (as per Chomsky’s ideas) without overgeneralizing and getting stuck.\n- See also: a broad set of related topics in AI, linguistics, and language technology (e.g., computational linguistics subfields, NLP applications, and related methods).\n- References and further reading: foundational texts include Natural Language Processing with Python (Bird, Klein, Loper) and Speech and Language Processing (Jurafsky & Martin); additional volumes by Kurdi cover NLP and computational linguistics.'}}

In [23]:
annotated_dataset_from_trace = create_dataset(
    name="annotated_dataset_from_trace",
    tags={"type": "annotated", "source": "wikipedia"},
)

In [24]:
annotated_dataset_from_trace.merge_records(annotated_data_list)